[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn app:app -b 0.0.0.0:$PORT"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
PORT = { default = "5000" }
FLASK_ENV = { default = "production" }