[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn app:app -b 0.0.0.0:$PORT --timeout 120"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
PORT = { default = "5000" }
FLASK_ENV = { default = "production" }
PYTHONUNBUFFERED = "1"
NIXPACKS_PYTHON_VERSION = "3.11"